name: tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: Unit
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.20.1'
        check-latest: true
        cache: true

    - run: go version
    - run: go mod download # Not required, used to segregate module download vs test times
    - env:
      run: make test
    - uses: codecov/codecov-action@v2
