name: tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  unit:
    name: Unit
    runs-on: 'ubuntu-22.04'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '~1.21'
        check-latest: true
        cache: true

    - run: go version
    - run: go mod download # Not required, used to segregate module download vs test times
    - run: make test-with-coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
